let shoppingList = ['pop tarts', 'ramen noodles', 'chips', 'salsa', 'coffee'];
shoppingList.push('fruit loops');
let x = shoppingList.indexOf('coffee');
// console.log(x);
shoppingList[x] = 'fair trade coffee';
// console.log(shoppingList);
x = shoppingList.indexOf('chips');
// console.log(x);
shoppingList[x] = 'rice';
// console.log(shoppingList);
x = shoppingList.indexOf('salsa');
// console.log(x);
shoppingList[x] = 'beans';
// console.log(shoppingList);
let shoppingCart = [];
shoppingCart.push(shoppingList[shoppingList.length-1]);
// console.log(shoppingCart);
shoppingList.pop();
shoppingCart.push(shoppingList[0]);
shoppingList.shift();
// console.log(shoppingList);
// console.log(shoppingCart);
while (shoppingList.length>0) {
    shoppingCart.push(shoppingList[0]);
    shoppingList.shift();
};
// console.log(shoppingList);
// console.log(shoppingCart);
shoppingCart.sort();
// console.log(shoppingCart);
shoppingCart.reverse();
console.log(shoppingCart.toString());